### ISSUE TITLE
failed to execute script acc_race_control

### ISSUE THREAD

**Issue by snajdan** [andreasntr/acc_race_control#1]
![acc_race_control_QvsezbDzUD](https://user-images.githubusercontent.com/2825791/118153939-bbebb900-b416-11eb-9777-04caaa14baf0.png)

and for remote control for online server, i need to enter TCP or UDP Port?

**Comment by andreasntr** [comment]
ACC uses the UDP protocol.

I can't debug your problem without additional info.
Please describe all the steps you've made before encountering the error (make sure you are using the latest version)

**Comment by snajdan** [comment]
1. downloaded the version from racedepartment (on my client pc)
2. typed in the broadcasting settings (port 9000, password etc.)
3. entered for remote control our serverip (dunno which server-port, TCP or UDP, you made it clear now)
4. saved the file
5. tried to start the executable and the error message showed

**Comment by andreasntr** [comment]
which version? Because the 1.0.4 was bugged

Anyway the remote control is not guaranteed to work since kunos has not made it clear. The custom ip is there to try but I only managed to send the connection request without receiving a response, maybe I didn't set up the right ports. But still it is not a 100% working feature

**Comment by snajdan** [comment]
was the latest version 2 days ago, was it 1.0.5?
anyway, i cant start the tool, because of the error. i only want to use it for live-stewarding with the VSC-feature :(

**Comment by andreasntr** [comment]
but why do you need to use the remote control?

The app can easily run on your pc if you join the session as spectator

EDIT: wait I think I got the problem. You're running the app with the ip of your server but it's not how it works. The ip is there only if you want to control an acc session (client) running on another pc. An acc server is not a client istance of the game.
You need to start the game on your pc, join as spectator and start the program (reset the ip as 127.0.0.1)

**Comment by andreasntr** [comment]
Closing this for inactiviy
